### ISSUE TITLE
False-positive incomplete match check for RISC-V simulators

### ISSUE THREAD

**Issue by arichardson** [rems-project/sail#191]
When building the (CHERI-)RISC-V csim targets I see various instances of the following warning:

```
Warning: Incomplete pattern match statement at sail-riscv/model/riscv_insts_base.sail:462.47-52:
462 |              let res : MemoryOpResult(bool) = match (width, sizeof(xlen)) {
    |                                               ^---^
    | 
The following expression is unmatched: (DOUBLE, 65)
```

I see two issues with this diagnostic: first it sounds like there is an actual missing match clause rather than a potentially missing one. And second this counter-example is impossible since sizeof(xlen) is a constant.

Would it be possible to avoid this warning for constant arguments?

Reduced test case:
```
$include <prelude.sail>

type xlen: Int = 64
enum word_width = {BYTE, HALF, WORD, DOUBLE}

val test  : (word_width) -> int
function test(width) = {
  match (width, sizeof(xlen)) {
    (BYTE, _)    => 1,
    (HALF, _)    => 2,
    (WORD, _)    => 4,
    (DOUBLE, 64) => 8
  }
}

function main((): unit) -> unit = {
  let _ = test(DOUBLE);
  ()
}
```

**Comment by arichardson** [comment]
Even simpler test case:
```
$include <prelude.sail>

type xlen: Int = 64

function main((): unit) -> unit = {
  let _: int = match (sizeof(xlen)) {
    32 => 4,
    64 => 8,
  };
  ()
}
```

Results in
```
Warning: Incomplete pattern match statement at match_const/test.sail:6.15-20:
6 |  let _: int = match (sizeof(xlen)) {
  |               ^---^
  | 
The following expression is unmatched: 65
```

**Comment by arichardson** [comment]
CC: @bauereiss @Alasdair

**Comment by Alasdair** [comment]
Right now it just looks at the contents of the unguarded match arms, and doesn't look at constraints on the possible values of the elements being passed in. This is fairly consistent with how completeness checking works for most programming languages - both Rust and OCaml will give a similar spurious counterexample, e.g.

```
309 | ..begin match 64 with
310 |   | 64 -> ()
311 |   end.
Warning 8 [partial-match]: this pattern-matching is not exhaustive.
Here is an example of a case that is not matched:
0
```

Whenever Sail proves a match statement M is complete it will attempt to generate a new equivalent match statement M' such that M' is 'obviously complete' in the sense that Coq or Isabelle will be able to tell that a direct translation of the match is complete (as they require all matches be complete to ensure totality). If we can't do that the entire match statement needs to be lifted into a monad and a redundant failure case is added which generates uglier code. For this reason it can be worth heeding these warnings and using wildcards to avoid them.

Fixing this would require checking pattern completeness w.r.t. constraints on the input type, which is quite a bit more sophisticated. I think we could do it because we already use a SMT solver, and it would probably be able to decide those constraints.

Might also be worth mentioning that if I fixed this I think it will complain that the 64-bit case is unreachable when `xlen = 32`, and I don't see any nice way to avoid that!

**Comment by Alasdair** [comment]
I'd also note that the above function `test` is quite odd. As the return type is just int you aren't gaining any type safety by matching on sizeof(xlen), it might be better to simply do:
```
val test  : (word_width) -> int
function test(width) = {
  match width {
    BYTE => 1,
    HALF => 2,
    WORD => 4,
    DOUBLE => 8
  }
}
```
If you want a total and type safe version of `test` that only allows 8 to be returned when `xlen = 64`, you'd need something like:
```
val test : word_width -> option({'n, (xlen == 64 & 'n == 8) | 'n in {1, 2, 4}. int('n)})

function test(width) = {
    match (width, sizeof(xlen)) {
        (BYTE, _) => Some(1),
        (HALF, _) => Some(2),
        (WORD, _) => Some(4),
        (DOUBLE, 64) => Some(8),
        (DOUBLE, _) => None(),
    }
}
```

**Comment by rmn30** [comment]
This 'pattern' occurs frequently in the sail-riscv code, [sometimes with the wildcard case](https://github.com/riscv/sail-riscv/blob/master/model/riscv_insts_aext.sail#L149) and [sometimes without](https://github.com/riscv/sail-riscv/blob/master/model/riscv_insts_base.sail#L397). Possibly the (slightly inelegant) solution here is just to add the wildcard where it is missing.

It's sad that this code is repeated so much. I have a vague memory that it used to be written more elegantly but that it didn't work well for theorem prover generation in previous versions of Sail. Maybe that is fixed now?

**Comment by arichardson** [comment]
Agreed that test is quite odd, I just created it as a minimal version of some of the functions @rmn30 linked.

I was not aware that this behaviour matches Rust/OCaml, so I guess we can close this issue and I'll fix the base RISC-V models to add the wildcard cases.

**Comment by Alasdair** [comment]
This has now been partially fixed on the following branch:

https://github.com/rems-project/sail/tree/int_pattern

Requires some testing before I can merge it but there shouldn't be any major problems. Some recent changes I have made internally have made this kind of pattern completeness checking technically feasible where it wasn't before.
```
val foo : forall 'n, 'n in {16, 32, 64}. int('n) -> unit

function foo(n) = {
    match n {
        16 => (),
        32 => (),
        64 => (),
    }
}
```
is now accepted as complete, and when a case is missed, i.e.
```
val foo : forall 'n, 'n in {16, 32, 64}. int('n) -> unit

function foo(n) = {
    match n {
        16 => (),
        32 => (),
    }
}
```
the correct case will appear in the error:
```
Warning: Incomplete pattern match statement at int_completeness2.sail:5.4-9:
5 |    match n {
  |    ^---^
  | 
The following expression is unmatched: 64
```

**Comment by Alasdair** [comment]
Should be fixed by https://github.com/rems-project/sail/pull/219
